version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "ember",
    "vue",
    "angularjs",
    "meteor",
    "angular"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
